export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const CAC_ADMIN={
  SELECT_NAVBAR : "SELECT NAVBAR BY CAC ADMIN",
  ADD_TO_ORGANIZATIONS_FILTER: "ADD TO ORGANIZATIONS FILTER",
  REMOVE_FROM_ORGANIZATIONS_FILTER:"REMOVE FROM ORGANIZATIONS FILTER",
  CLEAN_ORGANIZATIONS_FILTER:"REMOVE EVERYTHIBG FROM ORGANIZATION FILETER"
}
